# Generated by Django 3.0.2 on 2020-02-12 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('essayapp', '0002_auto_20200212_1530'),
    ]

    operations = [
        migrations.RenameField(
            model_name='essay1',
            old_name='title',
            new_name='topic',
        ),
    ]
