# Generated by Django 3.0.2 on 2020-02-13 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essayapp', '0004_auto_20200213_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essay2',
            name='date',
            field=models.CharField(max_length=150),
        ),
    ]
